"""add ocr_tasks table

Revision ID: 07c4ef8c648d
Revises: 73a1aa429490
Create Date: 2026-07-04 14:56:32.490035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '07c4ef8c648d'
down_revision: Union[str, None] = '73a1aa429490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_tasks',
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('student_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('ocr_result', sa.JSON(), nullable=True),
    sa.Column('grading_result', sa.JSON(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_ocr_tasks_batch_id'), 'ocr_tasks', ['batch_id'], unique=False)
    op.create_index(op.f('ix_ocr_tasks_status'), 'ocr_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_ocr_tasks_teacher_id'), 'ocr_tasks', ['teacher_id'], unique=False)
    op.drop_table('warning_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warning_logs',
    sa.Column('warning_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('warning_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('level', sa.VARCHAR(length=32), nullable=True),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('processed_by', sa.VARCHAR(length=64), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('processed_note', sa.TEXT(), nullable=True),
    sa.Column('notified_teacher', sa.BOOLEAN(), nullable=True),
    sa.Column('notified_parent', sa.BOOLEAN(), nullable=True),
    sa.Column('notified_student', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('warning_id')
    )
    op.drop_index(op.f('ix_ocr_tasks_teacher_id'), table_name='ocr_tasks')
    op.drop_index(op.f('ix_ocr_tasks_status'), table_name='ocr_tasks')
    op.drop_index(op.f('ix_ocr_tasks_batch_id'), table_name='ocr_tasks')
    op.drop_table('ocr_tasks')
    # ### end Alembic commands ###
