"""initial schema

Revision ID: 73a1aa429490
Revises: 
Create Date: 2026-07-04 04:22:53.834618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '73a1aa429490'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warning_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warning_logs',
    sa.Column('warning_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('warning_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('level', sa.VARCHAR(length=32), nullable=True),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('processed_by', sa.VARCHAR(length=64), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('processed_note', sa.TEXT(), nullable=True),
    sa.Column('notified_teacher', sa.BOOLEAN(), nullable=True),
    sa.Column('notified_parent', sa.BOOLEAN(), nullable=True),
    sa.Column('notified_student', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('warning_id')
    )
    # ### end Alembic commands ###
